/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Dashboard API
 * Dashboard REST API for managing customers, invoices, users, and revenues
 * OpenAPI spec version: 1.0
 */
import type {
  ActivityEvent,
  GetRecentEventsParams
} from './dashboardAPI.schemas';

import { dataApiFetch } from '../dataApiFetch';


/**
 * Retrieves the most recent activity events from the feed
 * @summary Get recent activity events
 */
export type getRecentEventsResponse200 = {
  data: ActivityEvent[]
  status: 200
}

export type getRecentEventsResponseSuccess = (getRecentEventsResponse200) & {
  headers: Headers;
};
;

export type getRecentEventsResponse = (getRecentEventsResponseSuccess)

export const getGetRecentEventsUrl = (params?: GetRecentEventsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/activity/recent?${stringifiedParams}` : `/api/v1/activity/recent`
}

export const getRecentEvents = async (params?: GetRecentEventsParams, options?: RequestInit): Promise<getRecentEventsResponse> => {

  return dataApiFetch<getRecentEventsResponse>(getGetRecentEventsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


