/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Dashboard API
 * Dashboard REST API for managing customers, invoices, users, and revenues
 * OpenAPI spec version: 1.0
 */
import type {
  CustomerCreate,
  CustomerRead,
  CustomerUpdate,
  SetImageBody
} from './dashboardAPI.schemas';

import { dataApiFetch } from '../dataApiFetch';


/**
 * Retrieves a specific customer by their ID
 * @summary Get customer by ID
 */
export type getCustomerByIdResponse200 = {
  data: CustomerRead
  status: 200
}

export type getCustomerByIdResponseSuccess = (getCustomerByIdResponse200) & {
  headers: Headers;
};
;

export type getCustomerByIdResponse = (getCustomerByIdResponseSuccess)

export const getGetCustomerByIdUrl = (id: string,) => {




  return `/api/v1/customers/${id}`
}

export const getCustomerById = async (id: string, options?: RequestInit): Promise<getCustomerByIdResponse> => {

  return dataApiFetch<getCustomerByIdResponse>(getGetCustomerByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}


/**
 * Update existing customer
 * @summary Update customer
 */
export type updateCustomerResponse200 = {
  data: CustomerRead
  status: 200
}

export type updateCustomerResponseSuccess = (updateCustomerResponse200) & {
  headers: Headers;
};
;

export type updateCustomerResponse = (updateCustomerResponseSuccess)

export const getUpdateCustomerUrl = (id: string,) => {




  return `/api/v1/customers/${id}`
}

export const updateCustomer = async (id: string,
    customerUpdate: CustomerUpdate, options?: RequestInit): Promise<updateCustomerResponse> => {

  return dataApiFetch<updateCustomerResponse>(getUpdateCustomerUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      customerUpdate,)
  }
);}


/**
 * Soft deletes a customer by its ID
 * @summary Delete customer
 */
export type deleteCustomerResponse200 = {
  data: number
  status: 200
}

export type deleteCustomerResponseSuccess = (deleteCustomerResponse200) & {
  headers: Headers;
};
;

export type deleteCustomerResponse = (deleteCustomerResponseSuccess)

export const getDeleteCustomerUrl = (id: string,) => {




  return `/api/v1/customers/${id}`
}

export const deleteCustomer = async (id: string, options?: RequestInit): Promise<deleteCustomerResponse> => {

  return dataApiFetch<deleteCustomerResponse>(getDeleteCustomerUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}


/**
 * Creates a new customer
 * @summary Create customer
 */
export type createCustomerResponse200 = {
  data: CustomerRead
  status: 200
}

export type createCustomerResponseSuccess = (createCustomerResponse200) & {
  headers: Headers;
};
;

export type createCustomerResponse = (createCustomerResponseSuccess)

export const getCreateCustomerUrl = () => {




  return `/api/v1/customers`
}

export const createCustomer = async (customerCreate: CustomerCreate, options?: RequestInit): Promise<createCustomerResponse> => {

  return dataApiFetch<createCustomerResponse>(getCreateCustomerUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      customerCreate,)
  }
);}


/**
 * Uploads an image of a customer
 * @summary Upload image of the customer
 */
export type setImageResponse200 = {
  data: string
  status: 200
}

export type setImageResponseSuccess = (setImageResponse200) & {
  headers: Headers;
};
;

export type setImageResponse = (setImageResponseSuccess)

export const getSetImageUrl = (id: string,) => {




  return `/api/v1/customers/${id}/image`
}

export const setImage = async (id: string,
    setImageBody: SetImageBody, options?: RequestInit): Promise<setImageResponse> => {
    const formData = new FormData();
formData.append(`file`, setImageBody.file);

  return dataApiFetch<setImageResponse>(getSetImageUrl(id),
  {
    ...options,
    method: 'POST'
    ,
    body:
      formData,
  }
);}


/**
 * Returns the total number of customers
 * @summary Get customer count
 */
export type getCustomerCountResponse200 = {
  data: number
  status: 200
}

export type getCustomerCountResponseSuccess = (getCustomerCountResponse200) & {
  headers: Headers;
};
;

export type getCustomerCountResponse = (getCustomerCountResponseSuccess)

export const getGetCustomerCountUrl = () => {




  return `/api/v1/customers/count`
}

export const getCustomerCount = async ( options?: RequestInit): Promise<getCustomerCountResponse> => {

  return dataApiFetch<getCustomerCountResponse>(getGetCustomerCountUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


/**
 * Retrieves a list of all customers
 * @summary Get all customers
 */
export type getAllCustomersResponse200 = {
  data: CustomerRead[]
  status: 200
}

export type getAllCustomersResponseSuccess = (getAllCustomersResponse200) & {
  headers: Headers;
};
;

export type getAllCustomersResponse = (getAllCustomersResponseSuccess)

export const getGetAllCustomersUrl = () => {




  return `/api/v1/customers/`
}

export const getAllCustomers = async ( options?: RequestInit): Promise<getAllCustomersResponse> => {

  return dataApiFetch<getAllCustomersResponse>(getGetAllCustomersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


