/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Dashboard API
 * Dashboard REST API for managing customers, invoices, users, and revenues
 * OpenAPI spec version: 1.0
 */
export interface InvoiceUpdate {
  /** @minLength 1 */
  status: string;
  amount?: number;
  /**
     * @minLength 1
     * @pattern ^[a-fA-F0-9]{24}$
     */
  customerId: string;
}

export interface CustomerRead {
  id?: string;
  name?: string;
  email?: string;
  image_url?: string;
}

export interface InvoiceRead {
  id?: string;
  status?: string;
  amount?: number;
  date?: string;
  customer?: CustomerRead;
}

export interface ObjectId {
  timestamp?: number;
  date?: string;
}

export interface CustomerUpdate {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  email: string;
  imageId?: ObjectId;
}

export interface InvoiceCreate {
  /** @minLength 1 */
  status: string;
  amount?: number;
  /**
     * @minLength 1
     * @pattern ^[a-fA-F0-9]{24}$
     */
  customer_id: string;
}

export interface PageRequest {
  page?: number;
  size?: number;
  sort?: string;
  order?: string;
  search?: string;
}

export interface PageReadInvoiceRead {
  totalPages?: number;
  currentPage?: number;
  itemsPerPage?: number;
  data?: InvoiceRead[];
}

export interface CustomerCreate {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  email: string;
}

export interface RevenueRead {
  id?: string;
  month?: string;
  revenue?: number;
}

export type ActivityEventMetadata = {[key: string]: unknown};

export interface ActivityEvent {
  id?: string;
  type?: string;
  actorId?: string;
  actorName?: string;
  timestamp?: string;
  metadata?: ActivityEventMetadata;
}

export type SetImageBody = {
  /** Image file */
  file: Blob;
};

export type GetPagesParams = {
/**
 * Search term to filter invoices
 */
searchTerm?: string;
/**
 * Page size
 */
size?: number;
};

export type GetLatestInvoiceParams = {
/**
 * Starting index
 */
indexFrom?: number;
/**
 * Ending index
 */
indexTo?: number;
};

export type GetInvoiceCountParams = {
/**
 * Filter by invoice status
 */
status?: string;
};

export type GetInvoiceAmountParams = {
/**
 * Filter by invoice status
 */
status?: string;
};

export type GetRecentEventsParams = {
/**
 * Maximum number of events to return
 */
limit?: number;
};

