/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Dashboard API
 * Dashboard REST API for managing customers, invoices, users, and revenues
 * OpenAPI spec version: 1.0
 */
import type {
  GetInvoiceAmountParams,
  GetInvoiceCountParams,
  GetLatestInvoiceParams,
  GetPagesParams,
  InvoiceCreate,
  InvoiceRead,
  InvoiceUpdate,
  PageReadInvoiceRead,
  PageRequest
} from './dashboardAPI.schemas';

import { dataApiFetch } from '../dataApiFetch';


/**
 * Retrieves a specific invoice by its ID
 * @summary Get invoice by ID
 */
export type getInvoiceByIdResponse200 = {
  data: InvoiceRead
  status: 200
}

export type getInvoiceByIdResponseSuccess = (getInvoiceByIdResponse200) & {
  headers: Headers;
};
;

export type getInvoiceByIdResponse = (getInvoiceByIdResponseSuccess)

export const getGetInvoiceByIdUrl = (id: string,) => {




  return `/api/v1/invoices/${id}`
}

export const getInvoiceById = async (id: string, options?: RequestInit): Promise<getInvoiceByIdResponse> => {

  return dataApiFetch<getInvoiceByIdResponse>(getGetInvoiceByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}


/**
 * Updates an existing invoice
 * @summary Update invoice
 */
export type updateInvoiceResponse200 = {
  data: InvoiceRead
  status: 200
}

export type updateInvoiceResponseSuccess = (updateInvoiceResponse200) & {
  headers: Headers;
};
;

export type updateInvoiceResponse = (updateInvoiceResponseSuccess)

export const getUpdateInvoiceUrl = (id: string,) => {




  return `/api/v1/invoices/${id}`
}

export const updateInvoice = async (id: string,
    invoiceUpdate: InvoiceUpdate, options?: RequestInit): Promise<updateInvoiceResponse> => {

  return dataApiFetch<updateInvoiceResponse>(getUpdateInvoiceUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      invoiceUpdate,)
  }
);}


/**
 * Soft deletes an invoice by its ID
 * @summary Delete invoice
 */
export type deleteInvoiceResponse200 = {
  data: number
  status: 200
}

export type deleteInvoiceResponseSuccess = (deleteInvoiceResponse200) & {
  headers: Headers;
};
;

export type deleteInvoiceResponse = (deleteInvoiceResponseSuccess)

export const getDeleteInvoiceUrl = (id: string,) => {




  return `/api/v1/invoices/${id}`
}

export const deleteInvoice = async (id: string, options?: RequestInit): Promise<deleteInvoiceResponse> => {

  return dataApiFetch<deleteInvoiceResponse>(getDeleteInvoiceUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}


/**
 * Creates a new invoice
 * @summary Create invoice
 */
export type createInvoiceResponse200 = {
  data: InvoiceRead
  status: 200
}

export type createInvoiceResponseSuccess = (createInvoiceResponse200) & {
  headers: Headers;
};
;

export type createInvoiceResponse = (createInvoiceResponseSuccess)

export const getCreateInvoiceUrl = () => {




  return `/api/v1/invoices`
}

export const createInvoice = async (invoiceCreate: InvoiceCreate, options?: RequestInit): Promise<createInvoiceResponse> => {

  return dataApiFetch<createInvoiceResponse>(getCreateInvoiceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      invoiceCreate,)
  }
);}


/**
 * Searches invoices with pagination support
 * @summary Search invoices
 */
export type searchInvoicesResponse200 = {
  data: PageReadInvoiceRead
  status: 200
}

export type searchInvoicesResponseSuccess = (searchInvoicesResponse200) & {
  headers: Headers;
};
;

export type searchInvoicesResponse = (searchInvoicesResponseSuccess)

export const getSearchInvoicesUrl = () => {




  return `/api/v1/invoices/search`
}

export const searchInvoices = async (pageRequest: PageRequest, options?: RequestInit): Promise<searchInvoicesResponse> => {

  return dataApiFetch<searchInvoicesResponse>(getSearchInvoicesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pageRequest,)
  }
);}


/**
 * Returns the total number of pages for search results
 * @summary Get page count
 */
export type getPagesResponse200 = {
  data: number
  status: 200
}

export type getPagesResponseSuccess = (getPagesResponse200) & {
  headers: Headers;
};
;

export type getPagesResponse = (getPagesResponseSuccess)

export const getGetPagesUrl = (params?: GetPagesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/invoices/pages?${stringifiedParams}` : `/api/v1/invoices/pages`
}

export const getPages = async (params?: GetPagesParams, options?: RequestInit): Promise<getPagesResponse> => {

  return dataApiFetch<getPagesResponse>(getGetPagesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


/**
 * Retrieves the most recent invoices with optional range parameters
 * @summary Get latest invoices
 */
export type getLatestInvoiceResponse200 = {
  data: InvoiceRead[]
  status: 200
}

export type getLatestInvoiceResponseSuccess = (getLatestInvoiceResponse200) & {
  headers: Headers;
};
;

export type getLatestInvoiceResponse = (getLatestInvoiceResponseSuccess)

export const getGetLatestInvoiceUrl = (params?: GetLatestInvoiceParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/invoices/latest?${stringifiedParams}` : `/api/v1/invoices/latest`
}

export const getLatestInvoice = async (params?: GetLatestInvoiceParams, options?: RequestInit): Promise<getLatestInvoiceResponse> => {

  return dataApiFetch<getLatestInvoiceResponse>(getGetLatestInvoiceUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


/**
 * Returns the total number of invoices, optionally filtered by status
 * @summary Get invoice count
 */
export type getInvoiceCountResponse200 = {
  data: number
  status: 200
}

export type getInvoiceCountResponseSuccess = (getInvoiceCountResponse200) & {
  headers: Headers;
};
;

export type getInvoiceCountResponse = (getInvoiceCountResponseSuccess)

export const getGetInvoiceCountUrl = (params?: GetInvoiceCountParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/invoices/count?${stringifiedParams}` : `/api/v1/invoices/count`
}

export const getInvoiceCount = async (params?: GetInvoiceCountParams, options?: RequestInit): Promise<getInvoiceCountResponse> => {

  return dataApiFetch<getInvoiceCountResponse>(getGetInvoiceCountUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


/**
 * Returns the sum of all invoice amounts, optionally filtered by status
 * @summary Get total invoice amount
 */
export type getInvoiceAmountResponse200 = {
  data: number
  status: 200
}

export type getInvoiceAmountResponseSuccess = (getInvoiceAmountResponse200) & {
  headers: Headers;
};
;

export type getInvoiceAmountResponse = (getInvoiceAmountResponseSuccess)

export const getGetInvoiceAmountUrl = (params?: GetInvoiceAmountParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/invoices/amount?${stringifiedParams}` : `/api/v1/invoices/amount`
}

export const getInvoiceAmount = async (params?: GetInvoiceAmountParams, options?: RequestInit): Promise<getInvoiceAmountResponse> => {

  return dataApiFetch<getInvoiceAmountResponse>(getGetInvoiceAmountUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


/**
 * Retrieves a list of all invoices
 * @summary Get all invoices
 */
export type getAllInvoicesResponse200 = {
  data: InvoiceRead[]
  status: 200
}

export type getAllInvoicesResponseSuccess = (getAllInvoicesResponse200) & {
  headers: Headers;
};
;

export type getAllInvoicesResponse = (getAllInvoicesResponseSuccess)

export const getGetAllInvoicesUrl = () => {




  return `/api/v1/invoices/`
}

export const getAllInvoices = async ( options?: RequestInit): Promise<getAllInvoicesResponse> => {

  return dataApiFetch<getAllInvoicesResponse>(getGetAllInvoicesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


