/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Dashboard API
 * Dashboard REST API for managing customers, invoices, users, and revenues
 * OpenAPI spec version: 1.0
 */
import type {
  RevenueRead
} from './dashboardAPI.schemas';

import { dataApiFetch } from '../dataApiFetch';


/**
 * Retrieves monthly revenue data
 * @summary Get all revenues
 */
export type getAllRevenuesResponse200 = {
  data: RevenueRead[]
  status: 200
}

export type getAllRevenuesResponseSuccess = (getAllRevenuesResponse200) & {
  headers: Headers;
};
;

export type getAllRevenuesResponse = (getAllRevenuesResponseSuccess)

export const getGetAllRevenuesUrl = () => {




  return `/api/v1/revenues/`
}

export const getAllRevenues = async ( options?: RequestInit): Promise<getAllRevenuesResponse> => {

  return dataApiFetch<getAllRevenuesResponse>(getGetAllRevenuesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


