/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export interface UserAdminUpdate {
  /**
     * @minLength 0
     * @maxLength 255
     */
  email?: string;
}

export interface GrantRead {
  id?: string;
  name?: string;
  description?: string;
}

export interface RoleRead {
  id?: string;
  name?: string;
  grants?: GrantRead[];
}

export interface UserAdminRead {
  id?: string;
  email?: string;
  emailVerified?: boolean;
  emailVerifiedAt?: string;
  locked?: boolean;
  failedLoginAttempts?: number;
  profileImageUrl?: string;
  roles?: RoleRead[];
  createdAt?: string;
  deletedAt?: string;
}

export interface GrantCreate {
  /**
     * @minLength 0
     * @maxLength 100
     */
  name: string;
  /**
     * @minLength 0
     * @maxLength 255
     */
  description?: string;
}

export interface EnsureGrantsResponse {
  created?: string[];
  alreadyExisted?: string[];
}

export interface OAuthClientCreated {
  id?: string;
  redirectUris?: string[];
  allowedScopes?: string[];
  clientSecret?: string;
}

export interface OAuthClientCreate {
  /** @minItems 1 */
  redirectUris: string[];
  /** @minItems 1 */
  allowedScopes: string[];
}

export interface TokenResponse {
  access_token?: string;
  token_type?: string;
  expires_in?: number;
  refresh_token?: string;
}

export interface OAuth2ErrorResponse {
  error?: string;
  error_description?: string;
}

export interface IntrospectionResponse {
  active?: boolean;
  sub?: string;
  exp?: number;
  scope?: string;
}

export interface MfaRequiredResponse {
  mfa_required?: boolean;
  mfa_token?: string;
}

export interface CreateRole {
  /**
     * @minLength 0
     * @maxLength 100
     */
  name: string;
}

export interface OAuthClientRead {
  id?: string;
  redirectUris?: string[];
  allowedScopes?: string[];
}

export type TokenBody = {
  /** `authorization_code` or `refresh_token` */
  grant_type: string;
  /** Authorization code (required for `authorization_code` grant) */
  code?: string;
  /** PKCE code verifier (required for `authorization_code` grant) */
  code_verifier?: string;
  /** Client ID (required for `authorization_code` grant) */
  client_id?: string;
  /** Redirect URI (required for `authorization_code` grant) */
  redirect_uri?: string;
  /** Client secret (required for confidential clients) */
  client_secret?: string;
  /** Refresh token (required for `refresh_token` grant) */
  refresh_token?: string;
};

export type RevokeBody = {
  /** The token to revoke */
  token: string;
  /** Hint about the token type: `access_token` or `refresh_token` */
  token_type_hint?: string;
};

export type IntrospectBody = {
  /** The token to introspect */
  token: string;
};

export type AuthorizeParams = {
/**
 * Must be `code`
 */
response_type: string;
/**
 * Client identifier
 */
client_id: string;
/**
 * Registered redirect URI
 */
redirect_uri: string;
/**
 * PKCE code challenge (RFC 7636)
 */
code_challenge: string;
/**
 * Must be `S256`
 */
code_challenge_method: string;
/**
 * Space-separated list of requested scopes
 */
scope?: string;
/**
 * Opaque value for CSRF protection, echoed back on redirect
 */
state?: string;
};

export type Authorize302 = { [key: string]: unknown };

export type SubmitAuthorizeBody = {
  /** Authorization request ID from the GET /authorize redirect */
  request_id: string;
  /** User email */
  username: string;
  /** User password */
  password: string;
};

export type SubmitAuthorize302 = { [key: string]: unknown };

export type SubmitMfaBody = {
  /** MFA token received from POST /authorize */
  mfa_token: string;
  /** 6-digit TOTP code from authenticator app */
  totp_code: string;
};

export type SubmitMfa302 = { [key: string]: unknown };

export type SearchUsersParams = {
/**
 * Search query (matched against email)
 */
q: string;
};

/**
 * @summary Get user by ID
 */
export type getUserByIdResponse200 = {
  data: Blob
  status: 200
}

export type getUserByIdResponse404 = {
  data: void
  status: 404
}

export type getUserByIdResponseSuccess = (getUserByIdResponse200) & {
  headers: Headers;
};
export type getUserByIdResponseError = (getUserByIdResponse404) & {
  headers: Headers;
};

export type getUserByIdResponse = (getUserByIdResponseSuccess | getUserByIdResponseError)

export const getGetUserByIdUrl = (id: string,) => {




  return `https://dashboard-spring-oauth.onrender.com/api/v2/user/${id}`
}

export const getUserById = async (id: string, options?: RequestInit): Promise<getUserByIdResponse> => {

  const res = await fetch(getGetUserByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUserByIdResponse
}



/**
 * Update mutable user fields (e.g. email)
 * @summary Update user
 */
export type updateUserResponse200 = {
  data: Blob
  status: 200
}

export type updateUserResponse404 = {
  data: void
  status: 404
}

export type updateUserResponse409 = {
  data: void
  status: 409
}

export type updateUserResponseSuccess = (updateUserResponse200) & {
  headers: Headers;
};
export type updateUserResponseError = (updateUserResponse404 | updateUserResponse409) & {
  headers: Headers;
};

export type updateUserResponse = (updateUserResponseSuccess | updateUserResponseError)

export const getUpdateUserUrl = (id: string,) => {




  return `https://dashboard-spring-oauth.onrender.com/api/v2/user/${id}`
}

export const updateUser = async (id: string,
    userAdminUpdate: UserAdminUpdate, options?: RequestInit): Promise<updateUserResponse> => {

  const res = await fetch(getUpdateUserUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userAdminUpdate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateUserResponse
}



/**
 * Soft-deletes the user account
 * @summary Delete user
 */
export type deleteUserResponse204 = {
  data: void
  status: 204
}

export type deleteUserResponse404 = {
  data: void
  status: 404
}

export type deleteUserResponseSuccess = (deleteUserResponse204) & {
  headers: Headers;
};
export type deleteUserResponseError = (deleteUserResponse404) & {
  headers: Headers;
};

export type deleteUserResponse = (deleteUserResponseSuccess | deleteUserResponseError)

export const getDeleteUserUrl = (id: string,) => {




  return `https://dashboard-spring-oauth.onrender.com/api/v2/user/${id}`
}

export const deleteUser = async (id: string, options?: RequestInit): Promise<deleteUserResponse> => {

  const res = await fetch(getDeleteUserUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteUserResponse
}



/**
 * Idempotently creates any grants from the provided list that do not already exist. Requires HTTP Basic authentication using the service secret. Intended to be called by downstream services on startup.
 * @summary Ensure grants exist
 */
export type ensureGrantsResponse200 = {
  data: Blob
  status: 200
}

export type ensureGrantsResponse401 = {
  data: void
  status: 401
}

export type ensureGrantsResponseSuccess = (ensureGrantsResponse200) & {
  headers: Headers;
};
export type ensureGrantsResponseError = (ensureGrantsResponse401) & {
  headers: Headers;
};

export type ensureGrantsResponse = (ensureGrantsResponseSuccess | ensureGrantsResponseError)

export const getEnsureGrantsUrl = () => {




  return `https://dashboard-spring-oauth.onrender.com/v2/service/grants/ensure`
}

export const ensureGrants = async (grantCreate: GrantCreate[], options?: RequestInit): Promise<ensureGrantsResponse> => {

  const res = await fetch(getEnsureGrantsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      grantCreate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: ensureGrantsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as ensureGrantsResponse
}



/**
 * Generates a new client secret. The old secret is immediately invalidated. The new secret is shown only once.
 * @summary Rotate client secret
 */
export type rotateSecretResponse200 = {
  data: Blob
  status: 200
}

export type rotateSecretResponse403 = {
  data: void
  status: 403
}

export type rotateSecretResponse404 = {
  data: void
  status: 404
}

export type rotateSecretResponseSuccess = (rotateSecretResponse200) & {
  headers: Headers;
};
export type rotateSecretResponseError = (rotateSecretResponse403 | rotateSecretResponse404) & {
  headers: Headers;
};

export type rotateSecretResponse = (rotateSecretResponseSuccess | rotateSecretResponseError)

export const getRotateSecretUrl = (id: string,) => {




  return `https://dashboard-spring-oauth.onrender.com/v2/oauthclients/${id}/secret`
}

export const rotateSecret = async (id: string, options?: RequestInit): Promise<rotateSecretResponse> => {

  const res = await fetch(getRotateSecretUrl(id),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rotateSecretResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as rotateSecretResponse
}



/**
 * Creates a client and returns the client secret. The secret is shown only once.
 * @summary Register a new OAuth client
 */
export type createClientResponse200 = {
  data: Blob
  status: 200
}

export type createClientResponse403 = {
  data: void
  status: 403
}

export type createClientResponseSuccess = (createClientResponse200) & {
  headers: Headers;
};
export type createClientResponseError = (createClientResponse403) & {
  headers: Headers;
};

export type createClientResponse = (createClientResponseSuccess | createClientResponseError)

export const getCreateClientUrl = () => {




  return `https://dashboard-spring-oauth.onrender.com/v2/oauthclients/`
}

export const createClient = async (oAuthClientCreate: OAuthClientCreate, options?: RequestInit): Promise<createClientResponse> => {

  const res = await fetch(getCreateClientUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oAuthClientCreate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createClientResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createClientResponse
}



/**
 * Issues access and refresh tokens. Supports `authorization_code` (with PKCE) and `refresh_token` grant types. Responses include `Cache-Control: no-store` and `Pragma: no-cache` per RFC 6749 §5.1.
 * @summary Token endpoint (RFC 6749 §3.2)
 */
export type tokenResponse200 = {
  data: Blob
  status: 200
}

export type tokenResponse400 = {
  data: Blob
  status: 400
}

export type tokenResponseSuccess = (tokenResponse200) & {
  headers: Headers;
};
export type tokenResponseError = (tokenResponse400) & {
  headers: Headers;
};

export type tokenResponse = (tokenResponseSuccess | tokenResponseError)

export const getTokenUrl = () => {




  return `https://dashboard-spring-oauth.onrender.com/v2/oauth2/token`
}

export const token = async (tokenBody: TokenBody, options?: RequestInit): Promise<tokenResponse> => {
    const formUrlEncoded = new URLSearchParams();
formUrlEncoded.append(`grant_type`, tokenBody.grant_type);
if(tokenBody.code !== undefined) {
 formUrlEncoded.append(`code`, tokenBody.code);
 }
if(tokenBody.code_verifier !== undefined) {
 formUrlEncoded.append(`code_verifier`, tokenBody.code_verifier);
 }
if(tokenBody.client_id !== undefined) {
 formUrlEncoded.append(`client_id`, tokenBody.client_id);
 }
if(tokenBody.redirect_uri !== undefined) {
 formUrlEncoded.append(`redirect_uri`, tokenBody.redirect_uri);
 }
if(tokenBody.client_secret !== undefined) {
 formUrlEncoded.append(`client_secret`, tokenBody.client_secret);
 }
if(tokenBody.refresh_token !== undefined) {
 formUrlEncoded.append(`refresh_token`, tokenBody.refresh_token);
 }

  const res = await fetch(getTokenUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body:
      formUrlEncoded,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: tokenResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as tokenResponse
}



/**
 * Revokes an access or refresh token. Always returns 200 even if the token is unknown or already revoked.
 * @summary Token revocation endpoint (RFC 7009)
 */
export type revokeResponse200 = {
  data: void
  status: 200
}

export type revokeResponseSuccess = (revokeResponse200) & {
  headers: Headers;
};
;

export type revokeResponse = (revokeResponseSuccess)

export const getRevokeUrl = () => {




  return `https://dashboard-spring-oauth.onrender.com/v2/oauth2/revoke`
}

export const revoke = async (revokeBody: RevokeBody, options?: RequestInit): Promise<revokeResponse> => {
    const formUrlEncoded = new URLSearchParams();
formUrlEncoded.append(`token`, revokeBody.token);
if(revokeBody.token_type_hint !== undefined) {
 formUrlEncoded.append(`token_type_hint`, revokeBody.token_type_hint);
 }

  const res = await fetch(getRevokeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body:
      formUrlEncoded,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: revokeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as revokeResponse
}



/**
 * Allows resource servers to validate a token and retrieve its metadata. Requires HTTP Basic authentication using the service client secret.
 * @summary Token introspection endpoint (RFC 7662)
 */
export type introspectResponse200 = {
  data: Blob
  status: 200
}

export type introspectResponse401 = {
  data: void
  status: 401
}

export type introspectResponseSuccess = (introspectResponse200) & {
  headers: Headers;
};
export type introspectResponseError = (introspectResponse401) & {
  headers: Headers;
};

export type introspectResponse = (introspectResponseSuccess | introspectResponseError)

export const getIntrospectUrl = () => {




  return `https://dashboard-spring-oauth.onrender.com/v2/oauth2/introspect`
}

export const introspect = async (introspectBody: IntrospectBody, options?: RequestInit): Promise<introspectResponse> => {
    const formUrlEncoded = new URLSearchParams();
formUrlEncoded.append(`token`, introspectBody.token);

  const res = await fetch(getIntrospectUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body:
      formUrlEncoded,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: introspectResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as introspectResponse
}



/**
 * Validates the authorization request and redirects the user-agent to the login page. Only `response_type=code` is supported. PKCE (`code_challenge` + `code_challenge_method`) is required.
 * @summary Authorization endpoint — initiate (RFC 6749 §4.1.1)
 */
export type authorizeResponse302 = {
  data: Blob
  status: 302
}

;
export type authorizeResponseError = (authorizeResponse302) & {
  headers: Headers;
};

export type authorizeResponse = (authorizeResponseError)

export const getAuthorizeUrl = (params: AuthorizeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://dashboard-spring-oauth.onrender.com/v2/oauth2/authorize?${stringifiedParams}` : `https://dashboard-spring-oauth.onrender.com/v2/oauth2/authorize`
}

export const authorize = async (params: AuthorizeParams, options?: RequestInit): Promise<authorizeResponse> => {

  const res = await fetch(getAuthorizeUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authorizeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authorizeResponse
}



/**
 * Called by the login form. Validates credentials and either issues an authorization code redirect or returns an `mfa_required` response if 2FA is enabled on the account.
 * @summary Authorization endpoint — submit credentials
 */
export type submitAuthorizeResponse200 = {
  data: Blob
  status: 200
}

export type submitAuthorizeResponse302 = {
  data: Blob
  status: 302
}

export type submitAuthorizeResponse400 = {
  data: Blob
  status: 400
}

export type submitAuthorizeResponseSuccess = (submitAuthorizeResponse200) & {
  headers: Headers;
};
export type submitAuthorizeResponseError = (submitAuthorizeResponse302 | submitAuthorizeResponse400) & {
  headers: Headers;
};

export type submitAuthorizeResponse = (submitAuthorizeResponseSuccess | submitAuthorizeResponseError)

export const getSubmitAuthorizeUrl = () => {




  return `https://dashboard-spring-oauth.onrender.com/v2/oauth2/authorize`
}

export const submitAuthorize = async (submitAuthorizeBody: SubmitAuthorizeBody, options?: RequestInit): Promise<submitAuthorizeResponse> => {
    const formUrlEncoded = new URLSearchParams();
formUrlEncoded.append(`request_id`, submitAuthorizeBody.request_id);
formUrlEncoded.append(`username`, submitAuthorizeBody.username);
formUrlEncoded.append(`password`, submitAuthorizeBody.password);

  const res = await fetch(getSubmitAuthorizeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body:
      formUrlEncoded,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: submitAuthorizeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as submitAuthorizeResponse
}



/**
 * Called after receiving `mfa_required=true`. Validates the TOTP code and completes the authorization code redirect.
 * @summary Authorization endpoint — complete MFA step
 */
export type submitMfaResponse302 = {
  data: Blob
  status: 302
}

export type submitMfaResponse400 = {
  data: Blob
  status: 400
}

export type submitMfaResponse401 = {
  data: Blob
  status: 401
}

;
export type submitMfaResponseError = (submitMfaResponse302 | submitMfaResponse400 | submitMfaResponse401) & {
  headers: Headers;
};

export type submitMfaResponse = (submitMfaResponseError)

export const getSubmitMfaUrl = () => {




  return `https://dashboard-spring-oauth.onrender.com/v2/oauth2/authorize/mfa`
}

export const submitMfa = async (submitMfaBody: SubmitMfaBody, options?: RequestInit): Promise<submitMfaResponse> => {
    const formUrlEncoded = new URLSearchParams();
formUrlEncoded.append(`mfa_token`, submitMfaBody.mfa_token);
formUrlEncoded.append(`totp_code`, submitMfaBody.totp_code);

  const res = await fetch(getSubmitMfaUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body:
      formUrlEncoded,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: submitMfaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as submitMfaResponse
}



/**
 * Unlocks the user account and resets failed login attempts
 * @summary Unblock user
 */
export type unblockUserResponse204 = {
  data: void
  status: 204
}

export type unblockUserResponse404 = {
  data: void
  status: 404
}

export type unblockUserResponse409 = {
  data: void
  status: 409
}

export type unblockUserResponseSuccess = (unblockUserResponse204) & {
  headers: Headers;
};
export type unblockUserResponseError = (unblockUserResponse404 | unblockUserResponse409) & {
  headers: Headers;
};

export type unblockUserResponse = (unblockUserResponseSuccess | unblockUserResponseError)

export const getUnblockUserUrl = (id: string,) => {




  return `https://dashboard-spring-oauth.onrender.com/api/v2/user/${id}/unblock`
}

export const unblockUser = async (id: string, options?: RequestInit): Promise<unblockUserResponse> => {

  const res = await fetch(getUnblockUserUrl(id),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: unblockUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as unblockUserResponse
}



/**
 * Creates a new password reset token; the scheduler will send the email on its next run
 * @summary Trigger password reset
 */
export type triggerPasswordResetResponse204 = {
  data: void
  status: 204
}

export type triggerPasswordResetResponse404 = {
  data: void
  status: 404
}

export type triggerPasswordResetResponseSuccess = (triggerPasswordResetResponse204) & {
  headers: Headers;
};
export type triggerPasswordResetResponseError = (triggerPasswordResetResponse404) & {
  headers: Headers;
};

export type triggerPasswordResetResponse = (triggerPasswordResetResponseSuccess | triggerPasswordResetResponseError)

export const getTriggerPasswordResetUrl = (id: string,) => {




  return `https://dashboard-spring-oauth.onrender.com/api/v2/user/${id}/reset-password`
}

export const triggerPasswordReset = async (id: string, options?: RequestInit): Promise<triggerPasswordResetResponse> => {

  const res = await fetch(getTriggerPasswordResetUrl(id),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: triggerPasswordResetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as triggerPasswordResetResponse
}



/**
 * Creates a new email verification token; the scheduler will send it on its next run
 * @summary Resend verification email
 */
export type resendVerificationEmailResponse204 = {
  data: void
  status: 204
}

export type resendVerificationEmailResponse404 = {
  data: void
  status: 404
}

export type resendVerificationEmailResponse409 = {
  data: void
  status: 409
}

export type resendVerificationEmailResponseSuccess = (resendVerificationEmailResponse204) & {
  headers: Headers;
};
export type resendVerificationEmailResponseError = (resendVerificationEmailResponse404 | resendVerificationEmailResponse409) & {
  headers: Headers;
};

export type resendVerificationEmailResponse = (resendVerificationEmailResponseSuccess | resendVerificationEmailResponseError)

export const getResendVerificationEmailUrl = (id: string,) => {




  return `https://dashboard-spring-oauth.onrender.com/api/v2/user/${id}/resend-verification`
}

export const resendVerificationEmail = async (id: string, options?: RequestInit): Promise<resendVerificationEmailResponse> => {

  const res = await fetch(getResendVerificationEmailUrl(id),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: resendVerificationEmailResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as resendVerificationEmailResponse
}



/**
 * Locks the user account, preventing login
 * @summary Block user
 */
export type blockUserResponse204 = {
  data: void
  status: 204
}

export type blockUserResponse404 = {
  data: void
  status: 404
}

export type blockUserResponse409 = {
  data: void
  status: 409
}

export type blockUserResponseSuccess = (blockUserResponse204) & {
  headers: Headers;
};
export type blockUserResponseError = (blockUserResponse404 | blockUserResponse409) & {
  headers: Headers;
};

export type blockUserResponse = (blockUserResponseSuccess | blockUserResponseError)

export const getBlockUserUrl = (id: string,) => {




  return `https://dashboard-spring-oauth.onrender.com/api/v2/user/${id}/block`
}

export const blockUser = async (id: string, options?: RequestInit): Promise<blockUserResponse> => {

  const res = await fetch(getBlockUserUrl(id),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: blockUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as blockUserResponse
}



/**
 * Returns all roles with their grants
 * @summary Get all roles
 */
export type getAllRolesResponse200 = {
  data: Blob
  status: 200
}

export type getAllRolesResponseSuccess = (getAllRolesResponse200) & {
  headers: Headers;
};
;

export type getAllRolesResponse = (getAllRolesResponseSuccess)

export const getGetAllRolesUrl = () => {




  return `https://dashboard-spring-oauth.onrender.com/api/v2/role/`
}

export const getAllRoles = async ( options?: RequestInit): Promise<getAllRolesResponse> => {

  const res = await fetch(getGetAllRolesUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAllRolesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllRolesResponse
}



/**
 * @summary Create a role
 */
export type createRoleResponse200 = {
  data: Blob
  status: 200
}

export type createRoleResponse409 = {
  data: void
  status: 409
}

export type createRoleResponseSuccess = (createRoleResponse200) & {
  headers: Headers;
};
export type createRoleResponseError = (createRoleResponse409) & {
  headers: Headers;
};

export type createRoleResponse = (createRoleResponseSuccess | createRoleResponseError)

export const getCreateRoleUrl = () => {




  return `https://dashboard-spring-oauth.onrender.com/api/v2/role/`
}

export const createRole = async (createRole: CreateRole, options?: RequestInit): Promise<createRoleResponse> => {

  const res = await fetch(getCreateRoleUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createRole,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createRoleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createRoleResponse
}



/**
 * Returns all grants
 * @summary Get all grants
 */
export type getAllGrantsResponse200 = {
  data: Blob
  status: 200
}

export type getAllGrantsResponseSuccess = (getAllGrantsResponse200) & {
  headers: Headers;
};
;

export type getAllGrantsResponse = (getAllGrantsResponseSuccess)

export const getGetAllGrantsUrl = () => {




  return `https://dashboard-spring-oauth.onrender.com/api/v2/grant/`
}

export const getAllGrants = async ( options?: RequestInit): Promise<getAllGrantsResponse> => {

  const res = await fetch(getGetAllGrantsUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAllGrantsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllGrantsResponse
}



/**
 * @summary Create a grant
 */
export type createGrantResponse200 = {
  data: Blob
  status: 200
}

export type createGrantResponse409 = {
  data: void
  status: 409
}

export type createGrantResponseSuccess = (createGrantResponse200) & {
  headers: Headers;
};
export type createGrantResponseError = (createGrantResponse409) & {
  headers: Headers;
};

export type createGrantResponse = (createGrantResponseSuccess | createGrantResponseError)

export const getCreateGrantUrl = () => {




  return `https://dashboard-spring-oauth.onrender.com/api/v2/grant/`
}

export const createGrant = async (grantCreate: GrantCreate, options?: RequestInit): Promise<createGrantResponse> => {

  const res = await fetch(getCreateGrantUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      grantCreate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createGrantResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createGrantResponse
}



/**
 * @summary Get OAuth client by ID
 */
export type getClientResponse200 = {
  data: Blob
  status: 200
}

export type getClientResponse404 = {
  data: void
  status: 404
}

export type getClientResponseSuccess = (getClientResponse200) & {
  headers: Headers;
};
export type getClientResponseError = (getClientResponse404) & {
  headers: Headers;
};

export type getClientResponse = (getClientResponseSuccess | getClientResponseError)

export const getGetClientUrl = (id: string,) => {




  return `https://dashboard-spring-oauth.onrender.com/v2/oauthclients/${id}`
}

export const getClient = async (id: string, options?: RequestInit): Promise<getClientResponse> => {

  const res = await fetch(getGetClientUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getClientResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getClientResponse
}



/**
 * @summary Delete an OAuth client
 */
export type deleteClientResponse204 = {
  data: void
  status: 204
}

export type deleteClientResponse403 = {
  data: void
  status: 403
}

export type deleteClientResponse404 = {
  data: void
  status: 404
}

export type deleteClientResponseSuccess = (deleteClientResponse204) & {
  headers: Headers;
};
export type deleteClientResponseError = (deleteClientResponse403 | deleteClientResponse404) & {
  headers: Headers;
};

export type deleteClientResponse = (deleteClientResponseSuccess | deleteClientResponseError)

export const getDeleteClientUrl = (id: string,) => {




  return `https://dashboard-spring-oauth.onrender.com/v2/oauthclients/${id}`
}

export const deleteClient = async (id: string, options?: RequestInit): Promise<deleteClientResponse> => {

  const res = await fetch(getDeleteClientUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteClientResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteClientResponse
}



/**
 * Case-insensitive partial match on email address
 * @summary Search users by email
 */
export type searchUsersResponse200 = {
  data: Blob
  status: 200
}

export type searchUsersResponseSuccess = (searchUsersResponse200) & {
  headers: Headers;
};
;

export type searchUsersResponse = (searchUsersResponseSuccess)

export const getSearchUsersUrl = (params: SearchUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://dashboard-spring-oauth.onrender.com/api/v2/user/search?${stringifiedParams}` : `https://dashboard-spring-oauth.onrender.com/api/v2/user/search`
}

export const searchUsers = async (params: SearchUsersParams, options?: RequestInit): Promise<searchUsersResponse> => {

  const res = await fetch(getSearchUsersUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: searchUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchUsersResponse
}



/**
 * @summary Get all users
 */
export type getAllUsersResponse200 = {
  data: Blob
  status: 200
}

export type getAllUsersResponseSuccess = (getAllUsersResponse200) & {
  headers: Headers;
};
;

export type getAllUsersResponse = (getAllUsersResponseSuccess)

export const getGetAllUsersUrl = () => {




  return `https://dashboard-spring-oauth.onrender.com/api/v2/user/`
}

export const getAllUsers = async ( options?: RequestInit): Promise<getAllUsersResponse> => {

  const res = await fetch(getGetAllUsersUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAllUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllUsersResponse
}



/**
 * @summary Get role by ID
 */
export type getRoleByIdResponse200 = {
  data: Blob
  status: 200
}

export type getRoleByIdResponse404 = {
  data: void
  status: 404
}

export type getRoleByIdResponseSuccess = (getRoleByIdResponse200) & {
  headers: Headers;
};
export type getRoleByIdResponseError = (getRoleByIdResponse404) & {
  headers: Headers;
};

export type getRoleByIdResponse = (getRoleByIdResponseSuccess | getRoleByIdResponseError)

export const getGetRoleByIdUrl = (id: string,) => {




  return `https://dashboard-spring-oauth.onrender.com/api/v2/role/${id}`
}

export const getRoleById = async (id: string, options?: RequestInit): Promise<getRoleByIdResponse> => {

  const res = await fetch(getGetRoleByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getRoleByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getRoleByIdResponse
}



/**
 * @summary Delete a role
 */
export type deleteRoleResponse204 = {
  data: void
  status: 204
}

export type deleteRoleResponse404 = {
  data: void
  status: 404
}

export type deleteRoleResponseSuccess = (deleteRoleResponse204) & {
  headers: Headers;
};
export type deleteRoleResponseError = (deleteRoleResponse404) & {
  headers: Headers;
};

export type deleteRoleResponse = (deleteRoleResponseSuccess | deleteRoleResponseError)

export const getDeleteRoleUrl = (id: string,) => {




  return `https://dashboard-spring-oauth.onrender.com/api/v2/role/${id}`
}

export const deleteRole = async (id: string, options?: RequestInit): Promise<deleteRoleResponse> => {

  const res = await fetch(getDeleteRoleUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteRoleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteRoleResponse
}



/**
 * @summary Get grant by ID
 */
export type getGrantByIdResponse200 = {
  data: Blob
  status: 200
}

export type getGrantByIdResponse404 = {
  data: void
  status: 404
}

export type getGrantByIdResponseSuccess = (getGrantByIdResponse200) & {
  headers: Headers;
};
export type getGrantByIdResponseError = (getGrantByIdResponse404) & {
  headers: Headers;
};

export type getGrantByIdResponse = (getGrantByIdResponseSuccess | getGrantByIdResponseError)

export const getGetGrantByIdUrl = (id: string,) => {




  return `https://dashboard-spring-oauth.onrender.com/api/v2/grant/${id}`
}

export const getGrantById = async (id: string, options?: RequestInit): Promise<getGrantByIdResponse> => {

  const res = await fetch(getGetGrantByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getGrantByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getGrantByIdResponse
}



/**
 * @summary Delete a grant
 */
export type deleteGrantResponse204 = {
  data: void
  status: 204
}

export type deleteGrantResponse404 = {
  data: void
  status: 404
}

export type deleteGrantResponseSuccess = (deleteGrantResponse204) & {
  headers: Headers;
};
export type deleteGrantResponseError = (deleteGrantResponse404) & {
  headers: Headers;
};

export type deleteGrantResponse = (deleteGrantResponseSuccess | deleteGrantResponseError)

export const getDeleteGrantUrl = (id: string,) => {




  return `https://dashboard-spring-oauth.onrender.com/api/v2/grant/${id}`
}

export const deleteGrant = async (id: string, options?: RequestInit): Promise<deleteGrantResponse> => {

  const res = await fetch(getDeleteGrantUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteGrantResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteGrantResponse
}
